### PR TITLE
Add Spotify data in learntidymodels

### PR DESCRIPTION
**Pull request by karaesmen**
This PR adds the `spotify` data set and it's manual in the package.
It also removes `palmerpenguins` from `Depends` and `Remotes`.

### CODE REVIEW

**Comment by topepo** [comment]
Try updating from master. The PR I just merged probably solves some (hopefully all) of the issues in the tests.

**Comment by juliasilge** [comment]
The reason this is failing right now is that palmerpenguins was removed from Remotes. It is not on CRAN yet so it needs to stay in Remotes. On the other hand, embed **is** back on CRAN, so it can come _out_ of Remotes.

Remotes should look like this:

```
Remotes:
    rstudio-education/gradethis,
    allisonhorst/palmerpenguins
```

**Comment by juliasilge** [comment]
Oh, unless none of tutorials are using palmerpenguins at all anymore? 🤔 In which case @karaesmen you need to remove it _both_ from Remotes _and_ Suggests.

Remotes is like an extra place where you say where to get a package from.

**Comment by juliasilge** [comment]
I'm going to close this very old PR 👍

**Pull request closed without merging**
